//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scraper_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastTable
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Time_Scraped { get; set; }
        public string Stock_Symbol { get; set; }
        public string Last_Price { get; set; }
        public string Change { get; set; }
        public string Change_Percent { get; set; }
        public string Volume { get; set; }
        public string Shares { get; set; }
        public string Average_Volume { get; set; }
        public string Market_Cap { get; set; }
    }
}
