//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scraper_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestSharpTable
    {
        public int Id { get; set; }
        public string TimeScraped { get; set; }
        public string Symbol { get; set; }
        public string LastPrice { get; set; }
        public string Change { get; set; }
        public string ChangePercent { get; set; }
    }
}
